version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: dependabot/bumps
  schedule:
    interval: weekly
    day: tuesday
    timezone: US/Eastern
    time: '06:00'
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint-config-standard
    versions:
    - 16.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.2
  - dependency-name: typedoc
    versions:
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.28
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.2
  - dependency-name: eslint-import-resolver-typescript
    versions:
    - 2.4.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.13.0
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.38.5
    - 2.40.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: "@rollup/plugin-babel"
    versions:
    - 5.2.3
    - 5.3.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
